---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install graft.nvim dependency
        uses: actions/checkout@v3
        with:
          repository: "tlj/graft.nvim"
          path: "deps/tlj/graft.nvim"
      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.2.1
        with:
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
